# This is a workflow for Connecting to an AML Workspace
name: Connect to Workspace
# Controls when the workflow will run
on: 
  workflow_call:
    inputs:
      resourceGroup:
        description: 'Resource Group'     
        required: true
        type: string
      workspace:
        description: 'Workspace Name'     
        required: true
        type: string
    secrets:
      creds:
        required: true
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "ConnectToWorkspace"
  ConnectToWorkspace:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{secrets.creds}}
          enable-AzPSSession: true
      - name: Upgrade Azure CLI
        run: |
          az upgrade --yes
      - name: Install ML extension 
        run: |
          az extension add --upgrade --name ml --version 2.30.0
          # az extension add --upgrade --name ml -y
          # sudo /opt/az/bin/python3 -m pip install azure-identity==1.17.1

      # - name: Update ML extension with allow-preview
      #   run: |
      #     az extension update --name ml --allow-preview true
      - name: list-models
        run:  az ml model list --resource-group ${{inputs.resourceGroup}} --workspace-name ${{inputs.workspace}}
        #run: az configure --defaults group=${{inputs.resourceGroup}} workspace=${{inputs.workspace}}
