name: create-compute

on: 
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
      size:  
        required: true
        type: string
      min_instances: 
        required: true
        type: number
      max_instances: 
        required: true
        type: number
      resource_group:   
        required: true
        type: string
      workspace_name:  
        required: true
        type: string
      cluster_tier: 
        required: false
        type: string
    secrets:
      creds:
        required: true
jobs:
  create-compute:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{secrets.creds}}
          enable-AzPSSession: true
      - name: Upgrade Azure CLI
        run: |
          az upgrade --yes
      - name: Install ML extension 
        run: |
          az extension add --upgrade --name ml --version 2.30.0
          # az extension add --upgrade --name ml -y
          # sudo /opt/az/bin/python3 -m pip install azure-identity==1.17.1

      - name: create-compute-default-tier
        if: ${{ inputs.cluster_tier == ''}}
        run: |
          az ml compute create --name ${{ inputs.cluster_name }} \
                                  --type AmlCompute \
                                  --tier "dedicated" \
                                  --size ${{ inputs.size }} \
                                  --min-instances ${{ inputs.min_instances }} \
                                  --max-instances ${{ inputs.max_instances }} \
                                  --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }}
      - name: create-compute-using-tier
        if: ${{ inputs.cluster_tier != ''}}
        run: |
          az ml compute create --name ${{ inputs.cluster_name }} \
                                  --type AmlCompute \
                                  --tier ${{ inputs.cluster_tier }} \
                                  --size ${{ inputs.size }} \
                                  --min-instances ${{ inputs.min_instances }} \
                                  --max-instances ${{ inputs.max_instances }} \
                                  --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }}

