name: register-featurestore

on:
  workflow_call:
    inputs:
      featurestore_file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      featurestore_name:
        required: true
        type: string
      set_param:
        required: false
        type: string
    secrets:
      creds:
        required: true

jobs:
  register-feature-store:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{secrets.creds}}
          enable-AzPSSession: true

      - name: Install ML extension
        run: az extension add -n ml -y

      - name: Update ML extension
        run: az extension update -n ml

      - name: Register Feature Store
        run: |
          FEATURESTORE_EXISTS=$(az ml feature-store list --workspace-name ${{ inputs.workspace_name }} -g ${{ inputs.resource_group }} -o tsv --query "[?name=='${{ inputs.featurestore_name }}'][name]" | wc -l)

          if [[ FEATURESTORE_EXISTS -ne 1 ]]; then
            echo "Creating feature store..."
            az ml feature-store create --name ${{ inputs.featurestore_name }} \
              --set ${{ inputs.set_param }} -f ${{ github.workspace }}/${{ inputs.featurestore_file }} \
              --workspace-name ${{ inputs.workspace_name }} -g ${{ inputs.resource_group }}
          else
            echo "Feature store already exists! Updating..."
            az ml feature-store update --name ${{ inputs.featurestore_name }} \
              --set ${{ inputs.set_param }} -f ${{ github.workspace }}/${{ inputs.featurestore_file }} \
              --workspace-name ${{ inputs.workspace_name }} -g ${{ inputs.resource_group }}
          fi
