name: register-environment

on:
  workflow_call:
    inputs:
      environment_file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      conda_file:
        required: false
        default: ""
        type: string
      dockerfile-location:
        required: false
        default: ""
        type: string
    secrets:
      creds:
        required: true
jobs:
  register-environment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{secrets.creds}}
          enable-AzPSSession: true
      - name: Upgrade Azure CLI
        run: |
          az upgrade --yes
      - name: Install ML extension 
        run: |
          az extension add --upgrade --name ml --version 2.30.0
          # az extension add --upgrade --name ml -y
          # sudo /opt/az/bin/python3 -m pip install azure-identity==1.17.1

      # - name: Update ML extension with allow-preview
      #   run: |
      #     az extension update --name ml --allow-preview true
      - name: create-environment-from-file-with-conda
        if: ${{ inputs.conda_file != ''}}
        run: |
          az ml environment create --file ${{ github.workspace }}/${{ inputs.environment_file }} --resource-group ${{ inputs.resource_group }} \
                                --workspace-name ${{ inputs.workspace_name }} --conda-file ${{ github.workspace }}/${{ inputs.conda_file }}
      - name: create-environment-from-file-without-conda
        if: ${{ inputs.conda_file == ''}}
        run: |
          az ml environment create --file ${{ github.workspace }}/${{ inputs.environment_file }} --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }}
      - name: create-environment-from-image
        if: ${{ inputs.dockerfile-location != ''}}
        run: |
          az ml environment create --file ${{ github.workspace }}/${{ inputs.environment_file }} --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }} --build-context ${{ github.workspace }}/${{ inputs.dockerfile-location }}
